name: Update from Develop

on:
  push:
    branches: [develop]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout develop
          git fetch origin
          git checkout develop-2
          git pull
          git rebase origin/develop
          git push --force origin develop-2
